# Generated by Django 5.1.1 on 2024-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_prise_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/photo",
                verbose_name="Изображение товара",
            ),
        ),
    ]
