# Generated by Django 4.2.2 on 2024-11-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_version_owner_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("set_published", "Can publish product"),
                    ("change_description", "Can change description"),
                    ("change_category", "Can change category"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
